apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: taskly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      initContainers:
        - name: wait-for-db
          image: postgres:16
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: taskly-secrets
                  key: DB_USER
          command: ["sh","-c","until pg_isready -h postgres -p 5432 -U $DB_USER; do echo waiting for db; sleep 2; done"]    
      containers:
        - name: backend
          image: taskly-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: taskly-secrets
                  key: ConnectionStrings__DefaultConnection
            - name: JWT__TokenKey
              valueFrom:
                secretKeyRef:
                  name: taskly-secrets
                  key: JWT__TokenKey     
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"  
          securityContext:
            readOnlyRootFilesystem: true