apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: taskly
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
