apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskly.backend.fullname" . }}
  labels:
    {{- include "taskly.backend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "taskly.backend.selectorLabels" . | nindent 4 }}
  type: {{ .Values.backend.service.type | default "ClusterIP" }}  
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
