apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskly.frontend.fullname" . }}-nginx
  labels:
    {{- include "taskly.frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen {{ .Values.frontend.containerPort | default 8080 }};
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }
    }
