name: .NET CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
      - 'Frontend/**'
  pull_request:
    branches: [ main ]

env:
  IMAGE_TAG: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || github.sha }}
  IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/taskly-backend
  IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/taskly-frontend

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore, Build, Tests (Backend)
        working-directory: ./Backend
        run: |
          dotnet restore Taskly.sln
          dotnet build Taskly.sln --configuration Release --no-restore
          dotnet test Taskly.sln --configuration Release --no-build --verbosity normal

      - name: Validate EF migrations
        working-directory: ./Backend
        run: dotnet ef migrations script --project Infrastructure --startup-project API --output migrations.sql     

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Frontend
        working-directory: ./Frontend/client
        run: |
          npm ci
          npm run build

  ghcr:
    if: github.event_name == 'push'
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_BACKEND }}:latest

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_FRONTEND }}:latest
