name: Helm Lint

on:
  pull_request:
    branches: [ main ]
    paths: [ 'deploy/helm/**' ]
  push:
    branches: [ main ]
    paths: [ 'deploy/helm/**' ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm lint
        run: helm lint ./deploy/helm/taskly
